# Generated by Django 4.2.5 on 2024-01-26 22:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Complaint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("violation_date", models.DateField()),
                ("place", models.CharField(max_length=255)),
                ("district", models.CharField(max_length=255)),
                ("state", models.CharField(max_length=255)),
                ("uploaded_file", models.FileField(upload_to="complaint_videos/")),
                ("comment", models.TextField()),
                ("comment2", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Initiated", "Initiated"),
                            ("Processed", "Processed"),
                            ("Reject", "Reject"),
                            ("Success", "Success"),
                        ],
                        default="Initiated",
                        max_length=10,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
