# Generated by Django 4.2.5 on 2024-01-26 22:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("complaint", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="complaint",
            name="comment2",
        ),
    ]
