# Generated by Django 4.2.5 on 2024-01-27 05:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("complaint", "0002_remove_complaint_comment2"),
    ]

    operations = [
        migrations.AddField(
            model_name="complaint",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="complaint",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
